version: "3.9"
volumes:
  prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      cassandra-cluster-network:
        ipv4_address: 172.18.0.102
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      cassandra-cluster-network:
        ipv4_address: 172.18.0.101
    ports:
      - 3000:3000

networks:
  cassandra-cluster-network:
    external: true
    name: cassandra-cluster-network
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.254